<?php

namespace tobimori\Seo;

use Kirby\Cms\App;
use Kirby\Cms\File;
use Kirby\Cms\Page;

/**
 * Alt texts of the images of the site & all pages the current user can see, one entry per `alt-text` field.
 * Not limited to the pages of the overview, as images are often stored on pages without SEO fields
 * (e.g. a media library page) & used elsewhere
 */
class ImageAudit
{
	/**
	 * States of alt texts, `ISSUES` need work
	 */
	public const FILTERS = ['missing', 'ai', 'decorative'];
	public const ISSUES = ['missing', 'ai'];

	/**
	 * @var array<string, array{id: string, model: \Kirby\Cms\File, fields: array<string>, field: string}>|null
	 */
	protected array|null $entries = null;

	/**
	 * Names of the alt text fields per file template
	 */
	protected array $fields = [];

	/**
	 * Entries by their id, see `id()`
	 *
	 * @return array<string, array{id: string, model: \Kirby\Cms\File, fields: array<string>, field: string}>
	 */
	public function entries(): array
	{
		if ($this->entries !== null) {
			return $this->entries;
		}

		$this->entries = [];
		$site = App::instance()->site();
		$pages = $site->index(true)->filter(fn (Page $page) => $page->isListable());

		foreach ([$site, ...$pages] as $parent) {
			foreach ($parent->files() as $file) {
				if ($file->type() !== 'image' || !$file->isListable()) {
					continue;
				}

				foreach ($this->fields($file) as $name) {
					$id = static::id($file, $name);
					$this->entries[$id] = [
						'id' => $id,
						'model' => $file,
						'fields' => [$name],
						'field' => $name,
					];
				}
			}
		}

		return $this->entries;
	}

	public function find(string $id): array|null
	{
		return $this->entries()[$id] ?? null;
	}

	/**
	 * Entries are per alt text field, as a file might have multiple of them
	 */
	public static function id(File $file, string $field): string
	{
		return "{$file->id()}#{$field}";
	}

	/**
	 * Names of the `alt-text` fields of the file's blueprint
	 *
	 * @return array<string>
	 */
	public function fields(File $file): array
	{
		return $this->fields[$file->template() ?? 'default'] ??= array_keys(array_filter(
			$file->blueprint()->fields(),
			fn ($field) => ($field['type'] ?? null) === 'alt-text'
		));
	}

	public function altText(array $entry): AltText
	{
		return AltText::parse($entry['model']->content()->get($entry['field'])->value());
	}

	/**
	 * Whether the entry is in the given state (see `FILTERS`), `issues` for any of the `ISSUES`
	 */
	public function has(array $entry, string $filter): bool
	{
		$alt = $this->altText($entry);

		return match ($filter) {
			'missing' => $alt->isMissing(),
			'ai' => !$alt->isMissing() && $alt->isAiGenerated(),
			'decorative' => $alt->isDecorative(),
			'issues' => array_filter(self::ISSUES, fn ($issue) => $this->has($entry, $issue)) !== [],
			default => false,
		};
	}

	/**
	 * Number of images per filter
	 */
	public function summary(): array
	{
		$summary = array_fill_keys(self::FILTERS, 0);

		foreach ($this->entries() as $entry) {
			foreach (self::FILTERS as $filter) {
				if ($this->has($entry, $filter)) {
					$summary[$filter]++;
				}
			}
		}

		return $summary;
	}

	/**
	 * Number of alt texts that are missing or generated by AI (& not reviewed yet)
	 */
	public function stats(): array
	{
		$stats = ['total' => 0, 'missing' => 0, 'ai' => 0];

		foreach ($this->entries() as $entry) {
			$alt = $this->altText($entry);
			$stats['total']++;

			if ($alt->isMissing()) {
				$stats['missing']++;
			} elseif ($alt->isAiGenerated()) {
				$stats['ai']++;
			}
		}

		return $stats;
	}
}
